version: "3"

volumes:
  django_sample_db_dev:

services:
  db:
    image: mysql:8.0.23
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - django_sample_db_dev:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci

  django:
    build:
      context: ./backend
    environment:
      DJANGO_DB_NAME: "${DB_DATABASE}"
      DJANGO_DB_USER: "${DB_USER}"
      DJANGO_DB_PASSWORD: "${DB_PASSWORD}"
      DJANGO_DB_HOST: db
      DJANGO_DB_PORT: "${DB_HOST}"
    ports:
      - "8000:8000"
    command: python manage.py runserver 0:8000
    volumes:
      - ./:/app/
    depends_on:
      - db
