# Generated by Django 3.1.7 on 2021-03-18 19:15

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='ID'),
        ),
    ]
