# Generated by Django 3.1.7 on 2021-03-09 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20210309_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='menu',
            new_name='board',
        ),
    ]
