# Generated by Django 3.1.7 on 2021-03-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20210301_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '댓글', 'verbose_name_plural': '댓글'},
        ),
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.URLField(default='', verbose_name='링크'),
            preserve_default=False,
        ),
    ]
